version: '1.0'

service:
  name: my-flask-app
  type: web
  description: Flask app serving a machine learning model
  port: 5000

build:
  context: .
  dockerfile: Dockerfile

# Optional: Environment variables
environment:
  - FLASK_ENV=production
  # - OLLAMA_API_KEY=your_api_key_here
  # - OTHER_ENV_VAR=value

# Optional: Define any secrets needed for the application
secrets:
  # - my_secret_key=secret_value

# Optional: Define any volumes if your application needs persistent storage
volumes:
  # - /path/on/host:/path/in/container

# Optional: Define the networks your service should connect to
networks:
  - default

# Optional: Health check configuration
health_check:
  path: /health
  interval: 30s
  timeout: 10s
